# Generated by Django 4.2.30 on 2026-05-12 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0005_create_campaign_managers_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='algorithm',
            field=models.CharField(default='python.random.shuffle', help_text='Identifier for the RNG algorithm. Bump algorithm_version if behavior changes.', max_length=64),
        ),
        migrations.AddField(
            model_name='raffle',
            name='algorithm_version',
            field=models.CharField(default='1.0', max_length=16),
        ),
        migrations.AddField(
            model_name='raffle',
            name='consumed_pool',
            field=models.BooleanField(default=True, help_text='True if participated_at was set on every pool member after the draw.'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='excluded_already_participated',
            field=models.BooleanField(default=True, help_text='True if the pool was restricted to submissions where participated_at is null.'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='filter_search',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='raffle',
            name='filter_store_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='participant_pool_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of submission IDs as they were passed to the shuffler.'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='prize_quantities',
            field=models.JSONField(blank=True, default=list, help_text='List of {prize_id, prize_name, quantity} so the audit page is readable even after a Prize is renamed or deleted.'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='seed',
            field=models.CharField(blank=True, help_text='Hex string passed to random.Random(seed). 32 chars from os.urandom(16) by default.', max_length=64),
        ),
        migrations.AddField(
            model_name='submission',
            name='eligibility_restoration_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='eligibility_restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='eligibility_restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_restorations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='participated_at',
            field=models.DateTimeField(blank=True, help_text='Set when this submission was last included in any raffle pool. Null = eligible for future draws.', null=True),
        ),
    ]
