# Generated by Django 4.2.30 on 2026-05-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_raffle_audit_and_submission_participated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='filter_search',
            field=models.CharField(blank=True, help_text='Free-text search string applied to the pool query at draw time. Blank = no filter.', max_length=200),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='filter_store_id',
            field=models.IntegerField(blank=True, help_text='Store PK used to filter the pool at draw time. Stored as int (not FK) to survive Store deletion.', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='eligibility_restoration_reason',
            field=models.CharField(blank=True, help_text='Staff-provided reason for restoring eligibility.', max_length=200),
        ),
        migrations.AlterField(
            model_name='submission',
            name='eligibility_restored_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when participated_at was cleared to re-admit this submission to the pool.', null=True),
        ),
    ]
