# Generated by Django 4.2.30 on 2026-05-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_futboleros_gt_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='group',
            field=models.CharField(blank=True, default='', help_text='Optional heading the store is grouped under in the dropdown (e.g. a city). Stores with no group render as a flat list.', max_length=120),
        ),
    ]
